server:
    port: 0

spring: 
    datasource: 
        url: jdbc:mysql://localhost:3306/db_user
        username: root
        password: 123456
    jpa:
        hibernate:
            ddl-auto: update
    application:
        name: user-service
    redis:
        host: 127.0.0.1
        port: 6379
    cloud:
        #Nacos
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848

#Dubbo
dubbo:
    application:
        name: user-service
    registry:
        address: nacos://127.0.0.1:8848
    